# Generated by Django 2.2.3 on 2019-07-17 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20190715_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipe.Tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
